### ISSUE TITLE
How to install it on Android?

### ISSUE THREAD

**Issue by dongliang0** [kavishdevar/aln#3]
I didn't understand the installation file where

**Comment by kavishdevar** [comment]
Hi!

> this requires root! To know more about why, read note below.

To install the app, check out the first testing release [here](/kavishdevar/aln/releases/latest). It will have all the required files.

This has a `libbluetooth_jni.so`. Create folder structure like this -

```
/data/local/tmp/overlay:
upper  work
/data/local/tmp/overlay/upper:
libbluetooth_jni.so
```
Now duplicate the `overlay` folder and name it `overlay2`

There is another file `bt.sh`

- Download this and place the `bt.sh` in `/data/adb/post-fs-data.d/`
- Create a folder in `/data/adb/modules/` and place the `libbluetooth_jni.so` file and the `module.prop` as the folder structure shows below.

```
/data/adb/modules/btl2capfix:
module.prop
/data/adb/modules/btl2capfix/system/lib64:
libbluetooth_jni.so
```

Now, you can use the app.

> p.s. the app has multiple bugs because it is a testing version. It might show an alert about the app not responding when your airpods get disconnected after you have the app running. And, if the app crashes often and doesn't work even if your airpods are connected, force stop the app, and start it again.

Let me know, if you have root, you were able to install and/or need any more help in setting up the required system files.

Root is currently required only to fix [an Android bug](https://issuetracker.google.com/issues/371713238). If you do not have root, all you can do for now is upvote the issue so that it is fixed with more priority!

Thank you!

**Comment by dongliang0** [comment]
Create folder structure in android?

**Comment by kavishdevar** [comment]
are you rooted?

**Comment by dongliang0** [comment]
I dont  have root and i have vote the issue

**Comment by kavishdevar** [comment]
Sorry, but as you might have read, currently this project requires root because of a bug in the android's bluetooth code, which makes communicating with AirPods without modyfing the system libraries of android impossible.

Thank you very much for the upvote! Until then, you could checkout the linux app in this same repository, if you are a linux user!

(Any help with upvotes or even a PR to fix the issue will be much appreciated :] thanks!)
